name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker build -t api-gateway:latest .

      - name: Run Tests
        run: docker run api-gateway:latest npm run test:cov

      - name: Push to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker tag api-gateway:latest ericamaya29/api-gateway:latest
      - run: docker push ericamaya29/api-gateway:latest